# Generated by Django 5.1.4 on 2025-02-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile Accessories', 'Mobile Accessories'), ('Computer Accessories', 'Computer Accessories')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
