# Generated by Django 5.1.4 on 2025-02-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0002_remove_product_whatsapp_number_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('product_title', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
